# This is a basic workflow to help you get started with Actions

name: Node.js

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  builder:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm test:unit
